### ISSUE TITLE
Update for v6 transfer

### ISSUE THREAD

**Issue by prestwich** [cpollard1001/storj.js#1] opened 2016-12-12 22:45 UTC
Websockets are so 2016. Get with the hip HTTP transfer.

See docs here: http://storj.github.io/core/tutorial-data-transfer.html

**Comment by retrohacker** [comment] 2016-12-12 22:50
Working on using `storj-lib` directly :-)

**Comment by prestwich** [comment] 2016-12-12 22:53
Is using `storj-lib` going to cause bloat? It has a lot of functions that the browser won't need, as I understand it.

**Comment by retrohacker** [comment] 2016-12-13 00:00
The bundle ends up being 1.8M unminified. A bit on the heavy side.

After you brought this up, I started looking into the implications of `storj-lib` in the browser. My main concern is it's use of ES6.

**Comment by retrohacker** [comment] 2016-12-13 00:01
Might selectively copy logic over
_cringes_

**Comment by retrohacker** [comment] 2016-12-13 00:15
Should chat about our options here soon. Hitting a fork in the road. Would like to share as much code between `storj-lib` and `storj.js` as possible.

**Comment by faddat** [comment] 2016-12-22 00:57
I think it makes more sense to use HTTP data transfer.  Also, 1.8MB?  No issue, I think.  

Web pages are enormous these days.

**Comment by retrohacker** [comment] 2016-12-22 16:47
Thanks @faddat! I agree re: HTTP for the first pass. The problem is HTTPS, farmers will need to issue certs and we will need to resolve to domain names to get around browser security. This also ties farmer availability to DNS resolution and brings up the question of NAT traversal strategies (and tunneling) for farmer's HTTPS endpoints. HTTP is incredibly straightforward (I have an example working now minus the `OPTIONS` endpoint), but HTTPS adds a layer of complexity that I'm not quite sure we want to take on. 

What I'm working on today is a SIPS proposal for `Contract` that includes the protocols the shards need to be served over for the contract to be considered valid. This will allow us to propose new protocols for different target platforms and let farmers adopt them as desired, essentially letting the market decide. From there, we can talk through our options for the browser protocol.

As of now, I'm thinking the initial alpha of storj.js will be HTTP only. Other protocols will be implemented pending a larger project we are kicking off the beginning of next year to make some changes to core. Those changes will make plugging in new protocols unobtrusive, perhaps even pushing protocol implementation out into userspace.

Apologies for the brain dump, wanted to capture this in an open forum since most of this has been talked about in-person or over Google Hangouts.

**Comment by retrohacker** [comment] 2016-12-22 16:58
Also, conversation is split between the issues here and https://community.storj.io/channel/storj-js

**Comment by retrohacker** [comment] 2016-12-22 17:11
Also, the current state re: size of the lib.

The initial release of the lib will require in a patched `storj-lib` that works in the browser. This will be a massive blob. Part of the project we are kicking off in January will be cleaning up the edges of the modules in the `storj-lib` code base.

Right now, requiring in the bits of `storj-lib` we need will result in nearly the entire codebase being browserfied. With the rewrite, we should be able to create targeted bundles for the browser. Each bundle would support a subset of `storj-lib` allowing users to bring in just the bits they need for their app. This should slim down the payload quite a bit.

**Comment by faddat** [comment] 2016-12-28 17:38
Actually, I really appreciate the brand up a lot. This is an emerging
category of web thing. I don't know exactly how to categorize it called
when it is part CDN and decentralized Network or Bitcoin. Certainly it is
100% peer to peer.

Do I understand you correctly that currently, in order to use this I have
to be willing to play copyright cop?

Unfortunately for all of us, I don't have the time or energy.  That said, I
really do want to implement code like this to create a decentralized video
hosting platform. I just don't want to have to play copyright come. If you
have thoughts on how I can do this using storj or something similar without
playing copyright cop, please let me know. I will try to respond more
quickly to your reply than I did this one.

I am open to Solutions like a windows or Android app.

**Comment by faddat** [comment] 2016-12-28 17:39
Oh and finally, the size of the app really does not matter to me. 2.8
megabytes is just not a big deal on today's web. If you don't agree with
this, please go to say news.google.com which I think we can easily agree is
well optimized.

I bet you, it is larger than 2.8 megabytes.

**Comment by retrohacker** [comment] 2016-12-29 18:07
Moving to storj org

**Closed as completed by retrohacker** 2016-12-29 18:07 UTC

**Comment by retrohacker** [comment] 2016-12-29 18:19
Sorry @faddat, I can't comment on copyright law 😞
